CREATE TABLE `dwd_volunteer_dim` (
user_id	comment '用户id',
wxg_nick_name	comment '在群中昵称',
type	comment '类型',
leader_id	comment '上级id',
stat	comment '状态',
join_date	comment '入职日期',
address_area_code	comment '地区编码',
address	comment '收货地址',
leave_date	comment '离职日期',
leave_type	comment '离职原因',
is_has_wxg	comment '是否有管理班级',
conf	comment '扩展配置',
ct	comment '创建时间',
ut	comment '更新时间',
ver	comment '版本',
del	comment '删除标志',
remark	comment 'NULL',
invitor_id	comment '邀请者id',
volunteer_type	comment '职级类型',
apply_time	comment '申请时间',
audit_time	comment '审核时间',
oper_id	comment '操作者id'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='班级运营的自愿者';
